<a href="https://colab.research.google.com/github/puritym8/Python-Data-Analysis/blob/main/numpydailypractice5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
61. Find the nearest value from a given value in an array (★★☆)


In [ ]:
arr = np.random.uniform(1, 12, 5)

# Setting a value 'v' to find the number closest to it in the array
v = 4

# Finding the value 'n' in 'arr' that is closest to 'v'
# Using np.abs(arr - v).argmin() to get the index of the element in 'arr' closest to 'v'
# Accessing the element using arr.flat[index] to get the closest value 'n'
n = arr.flat[np.abs(arr - v).argmin()]

# Printing the value 'n' that is closest to 'v'
print(n)

4.9475644923531465


In [ ]:
62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


In [ ]:
a = np.array([1, 2, 3])
b = np.array([0, 1, 2])

c = a.reshape(3, 1) @ b.reshape(1, 3)
print(c)

[[0 1 2]
 [0 2 4]
 [0 3 6]]


In [ ]:
63. Create an array class that has a name attribute (★★☆)*******


In [ ]:
class NamedArray(np.ndarray):
  def __new__(cls, array, name="no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj

  def __array_finalize__(self, obj):
    if obj is None:
      return
    self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


In [ ]:
64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)


In [ ]:
given_vector = np.array([1, 2, 3, 4, 5])

# Second vector containing indices
indices_vector = np.array([1, 3, 3, 4, 0])

# Create an array to store the result
result = np.zeros_like(given_vector)

# Loop through the indices and add 1 to corresponding elements in the result array
unique_indices, counts = np.unique(indices_vector, return_counts=True)
result[unique_indices] += counts

print("Original vector:", given_vector)
print("Indices vector:", indices_vector)
print("Result after adding 1 to elements indexed by second vector:", result)

Original vector: [1 2 3 4 5]
Indices vector: [1 3 3 4 0]
Result after adding 1 to elements indexed by second vector: [1 1 0 2 1]


In [ ]:
65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


In [ ]:
X =[1,2,3,4,5,6]
I =[1,3,9,3,4,1]

F =np.bincount(I,X)

print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)


In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [ ]:
67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)


In [ ]:
A =np.random.randint(0,10,(3,4,3,4))

sum=A.sum(axis=(-2,-1))

print(sum)
 # solution by flattening the last two dimensions into one # (useful for functions that don't accept tuples for axis argument)
sum=A.reshape(A.shape[:-2] +(-1,)).sum(axis=-1)

print(sum)

[[55 66 46 68]
 [58 53 41 52]
 [56 39 82 41]]
[[55 66 46 68]
 [58 53 41 52]
 [56 39 82 41]]


In [ ]:
68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)


In [ ]:
D =np.random.uniform(0,1,100)
S =np.random.randint(0,10,100)
D_sums =np.bincount(S, weights=D)
D_counts =np.bincount(S)
D_means =D_sums /D_counts

print(D_means)

[0.54491651 0.42414655 0.57017347 0.35133491 0.52581548 0.49334534
 0.70137336 0.43790575 0.51970812 0.46730656]


In [ ]:
69. How to get the diagonal of a dot product? (★★★)


In [ ]:
A =np.random.uniform(0,1,(5,5))
B =np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([1.25420507, 1.19330728, 0.83908756, 1.10161303, 1.07759659])

In [ ]:
70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


In [ ]:
nums = np.array([1, 2, 3, 4, 5])

p = 2

# Creating a new array 'new_nums' of length len(nums) + (len(nums) - 1) * p filled with zeros
new_nums = np.zeros(len(nums) + (len(nums) - 1) * (p))

# Filling the 'new_nums' array with elements from 'nums' at intervals of (p + 1)
new_nums[::p + 1] = nums

# Displaying the new array 'new_nums'
print(new_nums)

[1. 0. 0. 2. 0. 0. 3. 0. 0. 4. 0. 0. 5.]


In [ ]:
71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)


In [ ]:
# Creating a NumPy array 'nums1' consisting of ones with shape (5, 5, 3)
nums1 = np.ones((5, 5, 3))

# Creating another NumPy array 'nums2' consisting of threes with shape (5, 5)
nums2 = 3 * np.ones((5, 5))

# Displaying the original array 'nums1'
print("Original array:")
print(nums1)

# Performing element-wise multiplication of 'nums1' and 'nums2' along the second axis using None to add a new axis
new_array = nums1 * nums2[:, :, None]

# Displaying the new array obtained after the multiplication
print("\nNew array:")
print(new_array)

Original array:
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

New array:
[[[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


In [ ]:
72. How to swap two rows of an array? (★★★)


In [ ]:
num_arr = np.array([[1,3,1], [3,1,3], [2,9,2], [9,2,9]])

# Displaying the original array
print("Original array:")
print(num_arr)

# Using np.roll() method for swapping array along row
num_arr = np.roll(num_arr,2,axis=0)

print("\nArray after swapping the rows:")
print(num_arr)

Original array:
[[1 3 1]
 [3 1 3]
 [2 9 2]
 [9 2 9]]

Array after swapping the rows:
[[2 9 2]
 [9 2 9]
 [1 3 1]
 [3 1 3]]


In [ ]:
73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)


In [ ]:
triplets = [
    [(1, 2), (3, 4), (5, 6)],
    [(3, 4), (7, 8), (9, 10)],
    # Add the remaining triplets here...
]

# Set to store unique line segments
unique_segments = set()

# Iterate over each triplet
for triplet in triplets:
    # Extract vertices of the triangle
    vertex1, vertex2, vertex3 = triplet

    # Define line segments
    segments = [
        (vertex1, vertex2),
        (vertex2, vertex3),
        (vertex3, vertex1)
    ]

    # Add line segments to the set
    for segment in segments:
        unique_segments.add(segment)

# Print the set of unique line segments
print("Unique Line Segments:")
for segment in unique_segments:
    print(segment)

Unique Line Segments:
((9, 10), (3, 4))
((3, 4), (7, 8))
((5, 6), (1, 2))
((1, 2), (3, 4))
((3, 4), (5, 6))
((7, 8), (9, 10))


In [ ]:
74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


In [ ]:
def reconstruct_array_from_bincount(C):
    A = []
    for i, count in enumerate(C):
        A.extend([i] * count)
    return np.array(A)

# Example usage:
C = np.array([0, 1, 2, 1, 0, 0, 3])  # Example sorted bincount array
A = reconstruct_array_from_bincount(C)
print("Reconstructed array A:", A)
print("Bincount of reconstructed array A:", np.bincount(A))
print("Is np.bincount(A) equal to C?", np.array_equal(np.bincount(A), C))

Reconstructed array A: [1 2 2 3 6 6 6]
Bincount of reconstructed array A: [0 1 2 1 0 0 3]
Is np.bincount(A) equal to C? True


In [ ]:
75. How to compute averages using a sliding window over an array? (★★★)

In [5]:
def sliding_window_average(arr, window_size):
  """
  Calculates the average of a given array using a sliding window of the specified size.

  Args:
      arr (list): The input array.
      window_size (int): The size of the sliding window.

  Returns:
      list: A list of averages calculated using the sliding window.
  """

  result = []
  for i in range(len(arr) - window_size + 1):
    window = arr[i:i+window_size]
    average = np.mean(window)
    result.append(average)

  return result

arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
window_size = 3
result = sliding_window_average(arr, window_size)
print("Averages using a sliding window of size", window_size, ":", result)

Averages using a sliding window of size 3 : [2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]


In [ ]:
76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:




77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

82. Compute a matrix rank (★★★)

83. How to find the most frequent value in an array?

84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

88. How to implement the Game of Life using numpy arrays? (★★★)

89. How to get the n largest values of an array (★★★)

90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

91. How to create a record array from a regular array? (★★★)

92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

95. Convert a vector of ints into a matrix binary representation (★★★)

96. Given a two dimensional array, how to extract unique rows? (★★★)

97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

