<a href="https://colab.research.google.com/github/puritym8/Python-Data-Analysis/blob/main/numpydailypractice3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
31. How to ignore all numpy warnings (not recommended)?

In [ ]:
32. Is the following expressions true? (★☆☆)


In [3]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-3-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [ ]:
33. How to get the dates of yesterday, today and tomorrow? (★☆☆

In [6]:
# Calculating yesterday's date
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ", yesterday)

# Calculating today's date
today = np.datetime64('today', 'D')
print("Today: ", today)

# Calculating tomorrow's date using NumPy's datetime64 and timedelta64
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)

Yesterday:  2024-03-24
Today:  2024-03-25
Tomorrow:  2024-03-26


In [ ]:
34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [8]:
Julydates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Julydates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [9]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [ ]:
36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)



In [10]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[6. 3. 9. 8. 9. 7. 7. 0. 8. 4.]
[6. 3. 9. 8. 9. 7. 7. 0. 8. 4.]
[6. 3. 9. 8. 9. 7. 7. 0. 8. 4.]
[6 3 9 8 9 7 7 0 8 4]
[6. 3. 9. 8. 9. 7. 7. 0. 8. 4.]


In [ ]:
37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [11]:
Arr = np.zeros((5,5))
Arr += np.arange(5)
print(Arr)

# without broadcasting
ArithmeticError= np.tile(np.arange(0, 5), (5,1))
print(Arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [12]:
def generate():
   for n in range(15):
       yield n

# Creating a NumPy array 'nums' using 'fromiter' by converting the generator into a NumPy array of type 'float'
nums = np.fromiter(generate(), dtype=float, count=-1)

# Displaying the newly created array 'nums'
print("New array:")
print(nums)

New array:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


In [ ]:
39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)



In [14]:
arr = np.linspace(0, 1, 12, endpoint=True)[1:-1]


print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
40. Create a random vector of size 10 and sort it (★★☆)


In [16]:
arr = np.random.random(10)

arr.sort()

print(arr)

[0.12322743 0.24806943 0.31614386 0.34150517 0.43301068 0.46865763
 0.57006912 0.71955753 0.7441064  0.88706252]


In [ ]:
41. How to sum a small array faster than np.sum? (★★☆)


In [17]:
arr = np.arange(10)
np.add.reduce(arr)

45

In [ ]:
42. Consider two random array A and B, check if they are equal (★★☆)


In [18]:
# Generating the first array 'x' with 6 random integers (0 or 1) using np.random.randint()
x = np.random.randint(0, 2, 6)

# Printing the first generated array 'x'
print("First array:")
print(x)

# Generating the second array 'y' with 6 random integers (0 or 1) using np.random.randint()
y = np.random.randint(0, 2, 6)

# Printing the second generated array 'y'
print("Second array:")
print(y)

# Checking if the two arrays 'x' and 'y' are equal using np.allclose()
# This function returns True if the two arrays are element-wise equal within a tolerance
array_equal = np.allclose(x, y)

# Printing whether the two arrays are equal or not
print("Test above two arrays are equal or not!")
print(array_equal)

First array:
[0 0 0 0 1 1]
Second array:
[0 1 0 1 0 0]
Test above two arrays are equal or not!
False


In [ ]:
43. Make an array immutable (read-only) (★★☆)


In [20]:
import numpy as np

x = np.zeros(10)
x.flags.writeable = False

# Create a copy of the array
y = x.copy()

# Modify the copy
y[0] = 1

# Print the modified copy
print(y)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


In [21]:
z = np.random.random((10, 2))

# Extracting the first column as 'x' and the second column as 'y' from the array 'z'
x, y = z[:, 0], z[:, 1]

# Calculating the Euclidean distance (r) using the formula sqrt(x^2 + y^2)
r = np.sqrt(x**2 + y**2)

# Calculating the angles (t) using arctan2() function, which returns the arctangent of y/x in radians
t = np.arctan2(y, x)

# Displaying the calculated Euclidean distances (r)
print(r)

# Displaying the calculated angles (t) in radians
print(t)

[0.89959291 1.03296646 0.95469793 0.7670664  0.98465576 0.87048228
 0.84276868 0.83580096 1.08990011 0.84399698]
[1.5518637  0.53320912 0.28272502 0.6439185  0.35554894 1.33871005
 0.06593935 1.5502575  0.44566331 1.29250488]


In [ ]:
45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


In [22]:
x = np.random.random(15)

# Displaying the original array 'x'
print("Original array:")
print(x)

# Finding the index of the maximum value in the array using x.argmax()
# Replacing the maximum value with -1 using the index obtained from x.argmax()
x[x.argmax()] = -1

# Displaying the modified array where the maximum value has been replaced by -1
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.44315172 0.4481927  0.6551331  0.09781553 0.92968371 0.26001703
 0.18258948 0.26252342 0.39713496 0.12369284 0.15109038 0.91726587
 0.04772169 0.19190021 0.15937156]
Maximum value replaced by -1:
[ 0.44315172  0.4481927   0.6551331   0.09781553 -1.          0.26001703
  0.18258948  0.26252342  0.39713496  0.12369284  0.15109038  0.91726587
  0.04772169  0.19190021  0.15937156]
