<a href="https://colab.research.google.com/github/puritym8/Python-Data-Analysis/blob/main/numpydailypractice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
16. How to add a border (filled with 0's) around an existing array?

array = np.ones((3,3))
print(array)

array = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print(array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
17. What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


Object `expression` not found.


False

In [ ]:
array = np.diag([1,2,3,4], k=1)

print(array)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [ ]:
array = np.ones((8,8), dtype=int)
array[::2, 1::2] = 0
array[1::2, ::2] = 0

print("checkerboard pattern")

print(array)

checkerboard pattern
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(99,(6,7,8)))

In [ ]:
Create checkerboard 8 x 8 matrix using the tile function

array = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
22. Normalize a 5x5 random matrix (★☆☆)

Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.31973614 0.63053036 0.1148477  0.6447005  0.15998307]
 [0.02674631 0.12703743 0.84613817 0.26843376 0.62378309]
 [0.20744104 0.26634231 0.65828544 0.82678102 0.55769054]
 [0.30305808 0.05974956 0.52460976 0.         0.83271784]
 [1.         0.32577952 0.85891566 0.16934489 0.00349501]]


In [ ]:
Create a custom dtype that describes a color as four unsigned bytes (RGBA)


In [ ]:

 color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-34-950c5cb321c8>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [ ]:
24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


In [ ]:


Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


In [ ]:

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
26. What is the output of the following script? (★☆☆)


In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
This code has no syntax errors.
1j*Z
Z/1/1
Z<Z>Z


SyntaxError: invalid syntax (<ipython-input-45-d5e7646c456b>, line 1)

In [ ]:
28. What are the result of the following expressions?
print (np.array(0) / np.array(0))
print (np.array(0) // np.array(0))
print (np.array([np.nan]).astype(int).astype(float))



Object `expressions` not found.
nan
0
[-9.22337204e+18]


<ipython-input-46-89efdb584ae8>:2: RuntimeWarning: invalid value encountered in divide
  print (np.array(0) / np.array(0))
<ipython-input-46-89efdb584ae8>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print (np.array(0) // np.array(0))
<ipython-input-46-89efdb584ae8>:4: RuntimeWarning: invalid value encountered in cast
  print (np.array([np.nan]).astype(int).astype(float))


In [ ]:
29. How to round away from zero a float array ? (★☆☆)


In [ ]:

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[  4.   1.   9.  -3.  10.  -2.  10. -10.  -1.  -7.]


In [ ]:

30. How to find common values between two arrays? (★☆☆)


In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 4 8]
