<a href="https://colab.research.google.com/github/puritym8/Python-Data-Analysis/blob/main/numpydailypractice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

import numpy as np


#### 3. Create a null vector of size 10 (★☆☆)
def null_array(n):
  x= np.zeros(n)
  return (x)

print(null_array(10))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#### 2. Print the numpy version and the configuration (★☆☆)

import numpy as np

print(np.__version__)

1.25.2


In [6]:
#### 4. How to find the memory size of any array (★☆☆)

import numpy as np

x = np.array([23,5,7])

print("Size of the array: ", x.size)

print("Memory size of one array element in bytes: ", x.itemsize)

# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:", x.size * x.itemsize)



Size of the array:  3
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 24


In [ ]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

import numpy as np

print(np.info(np.add))



add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

x = np.zeros(10)
x[4] = 1

print (x)




[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [1]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

import numpy as np
v = np.arange(10, 50)

print (v)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:

#### 8. Reverse a vector (first element becomes last) (★☆☆)

import numpy as np

x = np.arange(1,100)

print("Reverse x:")

x = x[::-1]
print(x)


Reverse x:
[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1]


In [7]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

import numpy as np

x = np.arange(0,9). reshape(3,3)

print (x)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

indices = np.nonzero([1,2,0,0,4,0])

print(indices)

(array([0, 1, 4]),)


In [2]:
#### 11. Create a 3x3 identity matrix (★☆☆)

import numpy as np

array = np.identity(3)

print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
#### 12. Create a 3x3x3 array with random values (★☆☆)

import numpy as np

x = np.random.random((3, 3, 3))

print(x)


[[[0.94588085 0.70199676 0.12085183]
  [0.86253228 0.28660358 0.5884375 ]
  [0.19554478 0.41203264 0.36221675]]

 [[0.52039946 0.97563586 0.69549098]
  [0.84858572 0.45291608 0.28778073]
  [0.71521164 0.14782917 0.71363756]]

 [[0.86724258 0.65195466 0.70980763]
  [0.02442412 0.80690965 0.23692582]
  [0.73890188 0.60371698 0.09935046]]]


In [ ]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

import numpy as np

x = np.random.random((10,10,10))
print (x)

xmin, xmax = x.min(), x.max()

print("Minimum and Maximum Values:")
print(xmin, xmax)


In [2]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

import numpy as np

x = np.random.random(30)

print(x)

m = x.mean

print (m)

[0.15216487 0.84309313 0.37822349 0.06742812 0.2222377  0.7137605
 0.40503462 0.5097841  0.43425724 0.90318834 0.91665982 0.78328548
 0.79437967 0.24740541 0.0965135  0.10659963 0.70597491 0.7634886
 0.23606932 0.3497242  0.20252399 0.66345887 0.37915883 0.38917752
 0.64211695 0.75262388 0.09061167 0.63282352 0.53995867 0.21557979]
<built-in method mean of numpy.ndarray object at 0x7852c738f930>


In [9]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

z = np.arange(0,9).reshape(3,3)

print (z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
