<a href="https://colab.research.google.com/github/puritym8/Python-Data-Analysis/blob/main/numpydailypractice5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
61. Find the nearest value from a given value in an array (★★☆)


In [2]:
arr = np.random.uniform(1, 12, 5)

# Setting a value 'v' to find the number closest to it in the array
v = 4

# Finding the value 'n' in 'arr' that is closest to 'v'
# Using np.abs(arr - v).argmin() to get the index of the element in 'arr' closest to 'v'
# Accessing the element using arr.flat[index] to get the closest value 'n'
n = arr.flat[np.abs(arr - v).argmin()]

# Printing the value 'n' that is closest to 'v'
print(n)

4.9475644923531465


In [ ]:
62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


In [3]:
a = np.array([1, 2, 3])
b = np.array([0, 1, 2])

c = a.reshape(3, 1) @ b.reshape(1, 3)
print(c)

[[0 1 2]
 [0 2 4]
 [0 3 6]]


In [ ]:
63. Create an array class that has a name attribute (★★☆)*******


In [9]:
class NamedArray(np.ndarray):
  def __new__(cls, array, name="no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj

  def __array_finalize__(self, obj):
    if obj is None:
      return
    self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


In [ ]:
64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)


In [10]:
given_vector = np.array([1, 2, 3, 4, 5])

# Second vector containing indices
indices_vector = np.array([1, 3, 3, 4, 0])

# Create an array to store the result
result = np.zeros_like(given_vector)

# Loop through the indices and add 1 to corresponding elements in the result array
unique_indices, counts = np.unique(indices_vector, return_counts=True)
result[unique_indices] += counts

print("Original vector:", given_vector)
print("Indices vector:", indices_vector)
print("Result after adding 1 to elements indexed by second vector:", result)

Original vector: [1 2 3 4 5]
Indices vector: [1 3 3 4 0]
Result after adding 1 to elements indexed by second vector: [1 1 0 2 1]


In [ ]:
65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


In [11]:
X =[1,2,3,4,5,6]
I =[1,3,9,3,4,1]

F =np.bincount(I,X)

print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)


In [ ]:




67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

69. How to get the diagonal of a dot product? (★★★)

70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

72. How to swap two rows of an array? (★★★)

73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

75. How to compute averages using a sliding window over an array? (★★★)

76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

82. Compute a matrix rank (★★★)

83. How to find the most frequent value in an array?

84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

88. How to implement the Game of Life using numpy arrays? (★★★)

89. How to get the n largest values of an array (★★★)

90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

91. How to create a record array from a regular array? (★★★)

92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

95. Convert a vector of ints into a matrix binary representation (★★★)

96. Given a two dimensional array, how to extract unique rows? (★★★)

97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

